routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth.user'], function () {
    Route::prefix('posts')->name('posts.')->group(function () {
        Route::get('/', [PostController::class, 'index'])->name('index');
        Route::get('/add', [PostController::class, 'add'])->name('add');
        Route::post('/add', [PostController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [PostController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [PostController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [PostController::class, 'delete'])->name('delete');
    });

    Route::prefix('products')->name('products.')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index');
        Route::get('/lists', [ProductController::class, 'listProduct'])->name('lists');
        Route::get('/add', [ProductController::class, 'add'])->name('add');
        Route::post('/add', [ProductController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [ProductController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [ProductController::class, 'delete'])->name('delete');
    });
});

// Route::prefix('posts')->name('posts.')->group(function () {
//     Route::get('/', [PostController::class, 'index'])->name('index');
//     Route::get('/add', [PostController::class, 'add'])->name('add');
//     Route::post('/add', [PostController::class, 'create'])->name('create');
//     Route::get('/edit/{id}', [PostController::class, 'edit'])->name('edit');
//     Route::post('/edit/{id}', [PostController::class, 'update'])->name('update');
//     Route::get('/delete/{id}', [PostController::class, 'delete'])->name('delete');
// });

Route::prefix('categories')->name('categories.')->group(function () {
    Route::get('/', [CategoryController::class, 'index'])->name('index');
    Route::get('/add', [CategoryController::class, 'add'])->name('add');
    Route::post('/add', [CategoryController::class, 'create'])->name('create');
    Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit');
    Route::post('/edit/{id}', [CategoryController::class, 'update'])->name('update');
    Route::get('/delete/{id}', [CategoryController::class, 'delete'])->name('delete');
});

Route::prefix('products')->name('products.')->group(function () {
    Route::get('/', [ProductController::class, 'index'])->name('index');
});

Route::prefix('users')->name('users.')->group(function () {
    Route::get('/', [UserController::class, 'index'])->name('index');
    Route::get('/add', [UserController::class, 'add'])->name('add');
    Route::post('/add', [UserController::class, 'create'])->name('create');
    Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
    Route::post('/edit/{id}', [UserController::class, 'update'])->name('update');
    Route::get('/delete/{id}', [UserController::class, 'delete'])->name('delete');
});


Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::get('/home', [HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <header class="container">
    </header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Trang chủ</a>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item ">
                <a class="nav-link active" aria-current="page" href="{{ route("posts.index") }}">Trang bài viết</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link active" aria-current="page" href="{{ route("categories.index") }}">Trang Danh mục</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link active" aria-current="page" href="{{ route("users.index") }}">Trang User</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link active" aria-current="page" href="{{ route("products.index") }}">Trang Sản phẩm</a>
              </li>
              <li class="nav-item ">
                <a class="nav-link active" aria-current="page" href="{{ route("products.lists") }}">Trang chính</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container">
        <div class="content">
            @yield('content')
        </div>
    </div>
    <footer class="container d-flex justify-content-end">
        Copyright: 2024
    </footer>
</div>
@endsection