routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth.user'], function () {
    Route::prefix('posts')->name('posts.')->group(function () {
        Route::get('/', [PostController::class, 'index'])->name('index');
        Route::get('/add', [PostController::class, 'add'])->name('add');
        Route::post('/add', [PostController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [PostController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [PostController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [PostController::class, 'delete'])->name('delete');
    });

    Route::prefix('products')->name('products.')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index');
        Route::get('/lists', [ProductController::class, 'listProduct'])->name('lists');
        Route::get('/add', [ProductController::class, 'add'])->name('add');
        Route::post('/add', [ProductController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [ProductController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [ProductController::class, 'delete'])->name('delete');
    });
});

// Route::prefix('posts')->name('posts.')->group(function () {
//     Route::get('/', [PostController::class, 'index'])->name('index');
//     Route::get('/add', [PostController::class, 'add'])->name('add');
//     Route::post('/add', [PostController::class, 'create'])->name('create');
//     Route::get('/edit/{id}', [PostController::class, 'edit'])->name('edit');
//     Route::post('/edit/{id}', [PostController::class, 'update'])->name('update');
//     Route::get('/delete/{id}', [PostController::class, 'delete'])->name('delete');
// });

Route::prefix('categories')->name('categories.')->group(function () {
    Route::get('/', [CategoryController::class, 'index'])->name('index');
    Route::get('/add', [CategoryController::class, 'add'])->name('add');
    Route::post('/add', [CategoryController::class, 'create'])->name('create');
    Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit');
    Route::post('/edit/{id}', [CategoryController::class, 'update'])->name('update');
    Route::get('/delete/{id}', [CategoryController::class, 'delete'])->name('delete');
});

Route::prefix('products')->name('products.')->group(function () {
    Route::get('/', [ProductController::class, 'index'])->name('index');
});

Route::prefix('users')->name('users.')->group(function () {
    Route::get('/', [UserController::class, 'index'])->name('index');
    Route::get('/add', [UserController::class, 'add'])->name('add');
    Route::post('/add', [UserController::class, 'create'])->name('create');
    Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
    Route::post('/edit/{id}', [UserController::class, 'update'])->name('update');
    Route::get('/delete/{id}', [UserController::class, 'delete'])->name('delete');
});


Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::get('/home', [HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Post extends Model
{

    protected $table = 'posts';
    public function getAllPostAndCategory()
    {
        // $posts = DB::table('posts')->get();
        $posts = DB::table('posts')->leftJoin('category_post', 'posts.id', '=', 'category_post.post_id')
            ->leftJoin('categories', 'category_post.category_id', '=', 'categories.id')->select(
                'posts.*',
                DB::raw('GROUP_CONCAT(categories.name SEPARATOR \',\') as category_name',),
                // 'category_post.post_id as postid',
                // 'categories.id as category_id',
            )->groupBy('posts.id')->get();

        return $posts;
    }


    public function getAllCategory()
    {
        $categories = DB::table('categories')->get();
        return $categories;
    }

    public function categories()
    {
        return $this->belongsToMany('App\Models\Category');
    }
    use HasFactory;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category_post;
use App\Models\Category;
use App\Models\Post;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    private $posts;
    public function __construct()
    {
        $this->posts = new Post();
    }
    public function index()
    {
        $title = "Tất cả bài viết";

        $postList = $this->posts->getAllPostAndCategory();
        return view("posts.view", compact('postList', 'title'));
    }

    public function add()
    {
        $title = 'Thêm bài viết';
        $categoryList = $this->posts->getAllCategory();
        return view('posts.add', compact('categoryList', 'title'));
    }
    public function create(Request $request)
    {
        $data = new Post();
        $data->name = $request->name;
        $file = $request->thumbnail;
        $filename = date('YmdHi') . $file->getClientOriginalName();
        $data->thumbnail = $filename;
        $file->move(public_path('files'), $filename);
        $data->slug = $request->slug;
        $data->description = $request->description;
        $data->content = $request->content;
        $data->created_at = date('Y-m-d H:i:s');
        $data->save();
        if (!empty($request->categories)) {
            $list = explode(',', $request->categories);
            foreach ($list as $item) {

                $post_cate = new Category_post();
                $post_cate->category_id = $item;
                $post_cate->post_id = $data->id;
                $post_cate->save();
            }
        }
        return redirect()->route('posts.index');
    }

    public function edit($id, Request $request)
    {
        $title = 'Sửa bài viết';
        $post = Post::findOrFail($id);
        $categoryList = $this->posts->getAllCategory();
        $allPostAndCate = $this->posts->getAllPostAndCategory();
        return view('posts.edit', compact('post', 'categoryList', 'allPostAndCate', 'title'));
    }
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);
        $post->name = $request->name;
        $file = $request->thumbnail;
        $filename = date('YmdHi') . $file->getClientOriginalName();
        $post->thumbnail = $filename;
        $file->move(public_path('files'), $filename);
        $post->slug = $request->slug;
        $post->description = $request->description;
        $post->content = $request->content;
        $post->created_at = date('Y-m-d H:i:s');
        $post->save();
        if (!empty($request->categories)) {
            $list = explode(',', $request->categories);
            foreach ($list as $item) {
                $post_cate = Category_post::findOrFail($id);
                $post_cate->category_id = $item;
                $post_cate->post_id = $id;
                $post_cate->save();
            }
        };
        return redirect()->route('posts.index');
    }
    public function delete($id)
    {
        Post::destroy($id);
        return redirect()->route('posts.index');
    }
}

resources/views/posts/add.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')
<h3 class="d-flex justify-content-center">{{ $title }}</h3>

@if ($errors->any())
<div class="alert alert-danger">Dữ liệu nhập vào không hợp lệ</div>
@endif
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        <div class="mb-3">
            <div class="form-group">
                <label for="name">Tên bài viết</label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="form-group">
                <label for="thumbnail">Hình ảnh</label>
                <input type="file" class="form-control" id="thumbnail" name="thumbnail" required accept="image/*">
            </div>
            <div class="form-group">
                <label for="slug">Slug</label>
                <textarea class="form-control" id="slug" name="slug"></textarea>
            </div>
            <div class="form-group">
                <label for="description">Mô tả</label>
                <textarea class="form-control" id="description" name="description" required></textarea>
            </div>
            <div class="form-group">
                <label for="content">Nội dung</label>
                <textarea class="form-control" name="content" id="content"></textarea>
            </div>
            <div class="form-group">
                <label for="categories">Danh mục</label>

                <div class="form-check px-6">
                    <select name="slcategories" id="slcategories" onchange="onChange()" class="js-example-basic-multiple" multiple="multiple">
                        @foreach ($categoryList as $category)
                        <option value="{{ $category->id }}">{{ $category->name}}</option>
                        @endforeach
                    </select>
                </div>
                <input type="hidden" class="form-control" id="categories" name="categories">
            </div>
        </div>
        @csrf
        <button type="submit" class="btn btn-primary">Tạo bài viết</button>
        <a href=" {{ route('posts.index') }} " class="btn btn-warning">Quay lại</a>
    </form>
</div>
<script>
    $(document).ready(function() {
        $('.js-example-basic-multiple').select2({
            width: '50%'
        });
    });

    function onChange() {
        var value = $("#slcategories").val()
        $("#categories").val(value.toString());
    }
</script>
@endsection

resources/views/posts/edit.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')
<h3 class="d-flex justify-content-center">{{ $title }}</h3>

@if ($errors->any())
<div class="alert alert-danger">Dữ liệu nhập vào không hợp lệ</div>
@endif
<div class="container">
    <form method="POST" enctype="multipart/form-data">
        <div class="mb-3">
            <div class="form-group">
                <label for="name">Tên bài viết</label>
                <input type="text" class="form-control" id="name" name="name" required value="{{ $post->name }}">
            </div>
            <div class="form-group">
                <label for="thumbnail">Hình ảnh</label>
                <input type="file" class="form-control" id="thumbnail" name="thumbnail" required accept="image/*" value="{{ $post->thumbnail }}">
            </div>
            <div class="form-group">
                <label for="slug">Slug</label>
                <textarea class="form-control" id="slug" name="slug" value="{{ $post->slug }}"></textarea>
            </div>
            <div class="form-group">
                <label for="description">Mô tả</label>
                <textarea class="form-control" id="description" name="description" required value="{{ $post->description}} "></textarea>
            </div>
            <div class="form-group">
                <label for="content">Nội dung</label>
                <textarea class="form-control" name="content" id="content" value="{{ $post->content }}"></textarea>
            </div>
            <div class="form-group">
                <label for="categories">Danh mục</label>

                <div class="form-check px-6">
                    <select name="slcategories" id="slcategories" onchange="onChange()" class="js-example-basic-multiple" multiple="multiple">
                        @foreach ($categoryList as $category)
                        <option value="{{ $category->id }}">{{ $category->name}}</option>
                        @endforeach
                    </select>
                </div>
                <input type="hidden" class="form-control" id="categories" name="categories">
            </div>
        </div>
        @csrf
        <button type="submit" class="btn btn-primary">Sửa bài viết</button>
        <a href=" {{ route('posts.index') }} " class="btn btn-warning">Quay lại</a>
    </form>
</div>
<script>
    $(document).ready(function() {
        $('.js-example-basic-multiple').select2({
            width: '50%'
        });
    });

    function onChange() {
        var value = $("#slcategories").val()
        $("#categories").val(value.toString());
    }
</script>
@endsection

resources/views/posts/extendLayouts.blade.php
@extends('layouts.app')
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@yield('title')</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<body>
    <header class="container">
        <h3>Trang chủ</h3>
    </header>
    <div class="container">
        <div class="sidebar">
            <a class="badge bg-info text-wrap text-decoration-none" href="{{ route("posts.index") }}">Trang bài viết</a>
            <a class="badge bg-info text-wrap text-decoration-none" href="{{ route("categories.index") }}">Trang Danh mục</a>
        </div>
        <div class="content">
            @yield('content')
        </div>
    </div>
    <footer class="container d-flex justify-content-end">
        Copyright: 2024
    </footer>
</body>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</html>

resources/views/posts/view.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')
<div class="container">
    <h2 class="d-flex justify-content-center">{{$title}}</h2>
<a href=" {{ route('posts.add') }} " class="btn btn-primary my-2">Thêm bài viết</a>
<a href=" {{ route('home') }} " class="btn btn-warning">Quay lại</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th width="5%">STT</th>
            <th>Tên bài viết</th>
            <th>Hình ảnh</th>
            <th>Chuyên mục</th>
            <th>Mô tả</th>
            <th>Ngày tạo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if(!empty($postList))
        @foreach($postList as $key => $item)
        <tr>
            <td>{{$key +1}}</td>
            <td>{{$item->name}}</td>
            <td><img src=" files/{{ $item->thumbnail  }}" alt=" {{ $item->name }} " width="100px"></td>

            <td>{{ $item->category_name }}</td>

            <td>{{$item->description}}</td>
            <td>{{$item->created_at}}</td>
            <td>
                <a href="{{ route('posts.edit', ['id'=>$item->id]) }}" class="btn btn-primary">Sửa</a>
                <a href="{{ route('posts.delete', ['id'=>$item->id]) }}" class="btn btn-danger">Xóa</a>
            </td>
        </tr>
        @endforeach
        @else
        <tr>
            <td> Khong co nguoi dung</td>
        </tr>
        @endif
    </tbody>
</table>
</div>
@endsection