routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth.user'], function () {
    Route::prefix('posts')->name('posts.')->group(function () {
        Route::get('/', [PostController::class, 'index'])->name('index');
        Route::get('/add', [PostController::class, 'add'])->name('add');
        Route::post('/add', [PostController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [PostController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [PostController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [PostController::class, 'delete'])->name('delete');
    });

    Route::prefix('products')->name('products.')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index');
        Route::get('/lists', [ProductController::class, 'listProduct'])->name('lists');
        Route::get('/add', [ProductController::class, 'add'])->name('add');
        Route::post('/add', [ProductController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [ProductController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [ProductController::class, 'delete'])->name('delete');
    });
});

// Route::prefix('posts')->name('posts.')->group(function () {
//     Route::get('/', [PostController::class, 'index'])->name('index');
//     Route::get('/add', [PostController::class, 'add'])->name('add');
//     Route::post('/add', [PostController::class, 'create'])->name('create');
//     Route::get('/edit/{id}', [PostController::class, 'edit'])->name('edit');
//     Route::post('/edit/{id}', [PostController::class, 'update'])->name('update');
//     Route::get('/delete/{id}', [PostController::class, 'delete'])->name('delete');
// });

Route::prefix('categories')->name('categories.')->group(function () {
    Route::get('/', [CategoryController::class, 'index'])->name('index');
    Route::get('/add', [CategoryController::class, 'add'])->name('add');
    Route::post('/add', [CategoryController::class, 'create'])->name('create');
    Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit');
    Route::post('/edit/{id}', [CategoryController::class, 'update'])->name('update');
    Route::get('/delete/{id}', [CategoryController::class, 'delete'])->name('delete');
});

Route::prefix('products')->name('products.')->group(function () {
    Route::get('/', [ProductController::class, 'index'])->name('index');
});

Route::prefix('users')->name('users.')->group(function () {
    Route::get('/', [UserController::class, 'index'])->name('index');
    Route::get('/add', [UserController::class, 'add'])->name('add');
    Route::post('/add', [UserController::class, 'create'])->name('create');
    Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
    Route::post('/edit/{id}', [UserController::class, 'update'])->name('update');
    Route::get('/delete/{id}', [UserController::class, 'delete'])->name('delete');
});


Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::get('/home', [HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Category extends Model
{
    protected $fillable = [
        'name',
    ];
    protected $table = 'categories';
    public function getCAtegories()
    {
        $categories = DB::table('categories')->get();
        return $categories;
    }
    public function posts()
    {
        return $this->belongsToMany('App\Models\Post');
    }
    use HasFactory;
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    private $categories;
    public function __construct()
    {
        $this->categories = new Category();
    }
    public function index()
    {
        $title = 'Danh mục';
        $categoryList = $this->categories->getCAtegories();

        return view('categories.view', compact('title', 'categoryList'));
    }
    public function add()
    {
        $title = 'Thêm danh mục';
        return view('categories.add', compact('title'));
    }
    public function create(Request $request)
    {
        $data = new Category();
        $data->name = $request->name;
        $data->created_at = date('Y-m-d H:i:s');
        $data->save();
        return redirect()->route('categories.index');
    }

    public function edit($id)
    {
        $title = 'Sửa danh mục';
        $cate = Category::findOrFail($id);
        return view('categories.edit', compact('cate', 'title'));
    }
    public function update(Request $request, $id)
    {
        $cate = Category::findOrFail($id);
        $data = $request->all();
        $cate->update($data);
        return redirect()->route('categories.index');
    }
    public function delete($id)
    {
        Category::destroy($id);
        return redirect()->route('categories.index');
    }
}

resources/views/categories/add.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')
<h3 class="d-flex justify-content-center">{{ $title }}</h3>

@if ($errors->any())
<div class="alert alert-danger">Dữ liệu nhập vào không hợp lệ</div>
@endif
<div class="container">
    <form method="POST">
        <div class="mb-3">
            <div class="form-group">
                <label for="name">Tên Danh mục</label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
            @csrf
            <button type="submit" class="btn btn-primary">Tạo danh mục</button>
            <a href=" {{ route('categories.index') }} " class="btn btn-warning">Quay lại</a>
    </form>
</div>

@endsection

resources/views/categories/edit.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')
<h3 class="d-flex justify-content-center">{{ $title }}</h3>

@if ($errors->any())
<div class="alert alert-danger">Dữ liệu nhập vào không hợp lệ</div>
@endif
<div class="container">
    <form method="POST">
        @csrf
        <div class="mb-3">
            <div class="form-group">
                <label for="name">Tên Danh mục</label>
                <input type="text" class="form-control" id="name" name="name" required value="{{ $cate->name }}">
            </div>

            <button type="submit" class="btn btn-primary">Cập nhật</button>
            <a href=" {{ route('categories.index') }} " class="btn btn-warning">Quay lại</a>
    </form>
</div>

@endsection

resources/views/categories/view.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')
<div class="container">
    <h2 class="d-flex justify-content-center">{{$title}}</h2>
<a href=" {{ route('categories.add') }} " class="btn btn-primary my-2">Thêm Danh mục</a>
<a href=" {{ route('home') }} " class="btn btn-warning">Quay lại</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th width="5%">STT</th>
            <th>Tên danh mục</th>
            <th>Ngày tạo</th>
        </tr>
    </thead>
    <tbody>
        @if(!empty($categoryList))
        @foreach($categoryList as $key => $item)
        <tr>
            <td>{{$key +1}}</td>
            <td>{{$item->name}}</td>
            <td>{{$item->created_at}}</td>
            <td>
                <a href="{{ route('categories.edit', ['id'=>$item->id]) }}" class="btn btn-primary">Sửa</a>
                <a href=" {{ route('categories.delete', ['id'=>$item->id]) }}" class="btn btn-danger">Xóa</a>
            </td>
        </tr>
        @endforeach
        @else
        <tr>
            <td> Không có danh mục</td>
        </tr>
        @endif
    </tbody>
</table>
</div>
@endsection