routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth.user'], function () {
    Route::prefix('posts')->name('posts.')->group(function () {
        Route::get('/', [PostController::class, 'index'])->name('index');
        Route::get('/add', [PostController::class, 'add'])->name('add');
        Route::post('/add', [PostController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [PostController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [PostController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [PostController::class, 'delete'])->name('delete');
    });

    Route::prefix('products')->name('products.')->group(function () {
        Route::get('/', [ProductController::class, 'index'])->name('index');
        Route::get('/lists', [ProductController::class, 'listProduct'])->name('lists');
        Route::get('/add', [ProductController::class, 'add'])->name('add');
        Route::post('/add', [ProductController::class, 'create'])->name('create');
        Route::get('/edit/{id}', [ProductController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [ProductController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [ProductController::class, 'delete'])->name('delete');
    });
});

// Route::prefix('posts')->name('posts.')->group(function () {
//     Route::get('/', [PostController::class, 'index'])->name('index');
//     Route::get('/add', [PostController::class, 'add'])->name('add');
//     Route::post('/add', [PostController::class, 'create'])->name('create');
//     Route::get('/edit/{id}', [PostController::class, 'edit'])->name('edit');
//     Route::post('/edit/{id}', [PostController::class, 'update'])->name('update');
//     Route::get('/delete/{id}', [PostController::class, 'delete'])->name('delete');
// });

Route::prefix('categories')->name('categories.')->group(function () {
    Route::get('/', [CategoryController::class, 'index'])->name('index');
    Route::get('/add', [CategoryController::class, 'add'])->name('add');
    Route::post('/add', [CategoryController::class, 'create'])->name('create');
    Route::get('/edit/{id}', [CategoryController::class, 'edit'])->name('edit');
    Route::post('/edit/{id}', [CategoryController::class, 'update'])->name('update');
    Route::get('/delete/{id}', [CategoryController::class, 'delete'])->name('delete');
});

Route::prefix('products')->name('products.')->group(function () {
    Route::get('/', [ProductController::class, 'index'])->name('index');
});

Route::prefix('users')->name('users.')->group(function () {
    Route::get('/', [UserController::class, 'index'])->name('index');
    Route::get('/add', [UserController::class, 'add'])->name('add');
    Route::post('/add', [UserController::class, 'create'])->name('create');
    Route::get('/edit/{id}', [UserController::class, 'edit'])->name('edit');
    Route::post('/edit/{id}', [UserController::class, 'update'])->name('update');
    Route::get('/delete/{id}', [UserController::class, 'delete'])->name('delete');
});


Route::get('/login', [LoginController::class, 'login'])->name('login');
Route::get('/home', [HomeController::class, 'index'])->name('home');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Product extends Model
{
    protected $table = 'products';

    public function getProduct()
    {
        $product = DB::table('products')->get();
        return $product;
    }

    use HasFactory;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{

    private $products;

    public function __construct()
    {
        $this->products = new Product();
    }
    public function index()
    {
        $title = "Tất cả Sản phẩm";
        $productList = $this->products->getProduct();
        return view("products.view", compact("title", "productList"));
    }
    public function listProduct()
    {
        $title = "Danh sách Sản phẩm";
        $productList = $this->products->getProduct();
        return view("products.lists", compact("title", "productList"));
    }
    public function add()
    {
        $title = "Thêm sản phẩm";
        return view("products.add", compact("title"));
    }
    public function create(Request $request)
    {
        $product = new Product();
        $product->name = $request->name;
        $file = $request->image;
        $filename = date('YmdHi') . $file->getClientOriginalName();
        $product->image = $filename;
        $file->move(public_path('files'), $filename);
        $product->price = $request->price;
        $product->description = $request->description;
        $product->save();
        return redirect()->route('products.index');
    }

    public function edit($id)
    {
        $title = 'Sửa Sản phẩm';
        $product = Product::findOrFail($id);
        return view('products.edit', compact('title', 'product'));
    }

    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);
        $product->name = $request->name;
        $file = $request->image;
        $filename = date('YmdHi') . $file->getClientOriginalName();
        $file->move(public_path('files'), $filename);
        $product->image = $filename;
        $product->price = $request->price;
        $product->description = $request->description;
        $product->save();
        return redirect()->route('products.index');
    }


    public function delete($id)
    {
        $product = Product::findOrFail($id);
        $product->delete();
        return redirect()->route('products.index');
    }
}

resources/views/products/add.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')

<div class="container">
    <h3>{{$title}}</h3>
    <form method="post" enctype="multipart/form-data">
        @csrf
        <div class="mb-3">
            <div class="form-group">
                <label for="name">Tên Sản phẩm</label>
                <input type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="form-group">
                <label for="image">Hình ảnh</label>
                <input type="file" class="form-control" id="image" name="image" required accept="image/*">
            </div>
            <div class="form-group">
                <label for="price">Giá</label>
                <input type="number" class="form-control" id="price" name="price" required>
            </div>
            <div class="form-group">
                <label for="description">Mô tả</label>
                <input type="text" class="form-control" id="description" name="description" required>
            </div>
        </div>
        <button class="btn btn-primary" type="submit">Thêm mới</button>
        <a href=" {{ route('products.index') }} " class="btn btn-warning">Quay lại</a>
    </form>
</div>
@endsection

resources/views/products/edit.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')

<div class="container">
    <h3>{{$title}}</h3>
    <form method="post" enctype="multipart/form-data">
        @csrf
        <div class="mb-3">
            <div class="form-group">
                <label for="name">Tên Sản phẩm</label>
                <input value="{{$product->name}}" type="text" class="form-control" id="name" name="name" required>
            </div>
            <div class="form-group">
                <label for="image">Hình ảnh</label>
                <input value="{{$product->image}}" type="file" class="form-control" id="image" name="image" required accept="image/*">
            </div>
            <div class="form-group">
                <label for="price">Giá</label>
                <input value="{{$product->price}}" type="number" class="form-control" id="price" name="price" required>
            </div>
            <div class="form-group">
                <label for="description">Mô tả</label>
                <input value="{{$product->description}}" type="text" class="form-control" id="description" name="description" required>
            </div>
        </div>
        <button class="btn btn-primary" type="submit">Sửa</button>
        <a href=" {{ route('products.index') }} " class="btn btn-warning">Quay lại</a>
    </form>
</div>
@endsection

resources/views/products/lists.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')
<div class="container">
    <h2 class="d-flex justify-content-center">{{$title}}</h2>
    <a href=" {{ route('home') }} " class="btn btn-warning my-2">Quay lại</a>
    <div class="row flex">
        @if(!empty($productList))
        @foreach ($productList as $item)
        <div class="col-3">
            <div class="card" style="width: 18rem;">
                <div class="card-body">
                  <h5 class="card-title">{{$item->name}}</h5>
                  <img src="/files/{{$item->image}}" width="100px" height="100px">
                  <h6 class="card-subtitle my-2 text-muted">{{$item->price}}đ</h6>
                  <a href="#" class="card-link">Thêm vào giỏ hàng</a>
                  <a href="#" class="card-link">Chi tiết</a>

                </div>
            </div>
        </div>
        @endforeach
        @else
        <p>Khong co san pham</p>
        @endif
    </div>
</div>
@endsection

resources/views/products/view.blade.php
@extends('home')
@section('title')
{{$title}}
@endsection
@section('content')
<div class="container">
    <h2 class="d-flex justify-content-center">{{$title}}</h2>
<a href=" {{ route('products.add') }} " class="btn btn-primary my-2">Thêm Sản phẩm</a>
<a href=" {{ route('home') }} " class="btn btn-warning">Quay lại</a>
<table class="table table-bordered">
    <thead>
        <tr>
            <th width="5%">STT</th>
            <th>Tên Sản phẩm</th>
            <th>Hình ảnh</th>
            <th>Giá</th>
            <th>Mô tả</th>
            <th>Ngày tạo</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if(!empty($productList))
        @foreach($productList as $key => $item)
        <tr>
            <td>{{$key +1}}</td>
            <td>{{$item->name}}</td>
            <td><img src="/files/{{$item->image}}" alt=" {{ $item->name }} " width="100px"></td>

            <td>{{ $item->price }}đ</td>

            <td>{{$item->description}}</td>
            <td>{{$item->created_at}}</td>
            <td>
                <a href="{{ route('products.edit', ['id'=>$item->id]) }}" class="btn btn-primary">Sửa</a>
                <a href="{{ route('products.delete', ['id'=>$item->id]) }}" class="btn btn-danger">Xóa</a>
            </td>
        </tr>
        @endforeach
        @else
        <tr>
            <td> Khong co nguoi dung</td>
        </tr>
        @endif
    </tbody>
</table>
</div>
@endsection